
INSERT INTO USERS(USERNAME, PASSWORD) VALUES ('marco', '$2a$10$IeCHsHgY02qa0mb5R26Pz.QTVH5q7E6BPydSnj4pt8QFyW/T26mhC');
INSERT INTO USERS(USERNAME, PASSWORD) VALUES ('mateo', '$2a$10$0maK8dkPsnKh53oMpZIubun1gvMSpAun./2M0EZ9elu.s.LhM2l4K');
INSERT INTO USERS(USERNAME, PASSWORD) VALUES ('ana', '$2a$10$v6qobdvJRW0q3CNQf9klJeHE./d.hH.Kg3jYjqc0l23mP/GWMy49.');


INSERT INTO STATE_TASK(DESCRIPTION) VALUES ('PROGRESS');
INSERT INTO STATE_TASK(DESCRIPTION) VALUES ('INCOMPLETE');
INSERT INTO STATE_TASK(DESCRIPTION) VALUES ('COMPLETE');

