CREATE SEQUENCE "USERS_IDENTITY" START WITH 1 INCREMENT BY 1;
CREATE TABLE USERS(
    USER_ID INTEGER DEFAULT NEXTVAL('USERS_IDENTITY') NOT NULL PRIMARY KEY,
    USERNAME CHARACTER VARYING(255) NOT NULL,
    PASSWORD CHARACTER VARYING(255) NOT NULL
);


CREATE SEQUENCE "STATE_TASK_IDENTITY" START WITH 1 INCREMENT BY 1;
CREATE TABLE STATE_TASK(
    ID_STATE_TASK INTEGER DEFAULT NEXTVAL('STATE_TASK_IDENTITY') NOT NULL PRIMARY KEY,
    DESCRIPTION CHARACTER VARYING(255) NOT NULL

);


CREATE SEQUENCE "TASK_IDENTITY" START WITH 1 INCREMENT BY 1;
CREATE TABLE TASK(
    ID INTEGER DEFAULT NEXTVAL('TASK_IDENTITY') NOT NULL PRIMARY KEY,
    DESCRIPTION CHARACTER VARYING(255) NOT NULL,
	STATE_TASK_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	FOREIGN KEY (STATE_TASK_ID) REFERENCES STATE_TASK(ID_STATE_TASK),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);