
spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  application:
    name: task
  datasource:
    url: jdbc:h2:mem:task
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jackson:
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080


security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 360000 # 1 minute in milliseconds


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true



